apiVersion: v1
kind: Secret
metadata:
  name: cast-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.cast.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.cast.postgres.password }}
  POSTGRES_DB: {{ .Values.cast.postgres.db }}
