apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: {{ .Values.cast.service.port }}
      targetPort: {{ .Values.cast.service.targetPort }}
  type: {{ .Values.cast.service.type }}
