apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-postgres-pv
  annotations:
    meta.helm.sh/release-name: "app"
    meta.helm.sh/release-namespace: "dev"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/cast-postgres
