apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/cast-postgres
