apiVersion: v1
kind: Secret
metadata:
  name: movie-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.movie.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.movie.postgres.password }}
  POSTGRES_DB: {{ .Values.movie.postgres.db }}
