apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-postgres-pv
  namespace: standard
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  hostPath:
    path: /mnt/data
