apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: standard
spec:
  selector:
    app: cast-service
    spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
