apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  namespace: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      initContainers: 
        - name: wait-for-db
          image: postgres:12.1-alpine
          command: ['sh', '-c', 'until pg_isready -h movie-db -p 5432 -U $(POSTGRES_USER); do echo waiting for postgres; sleep 2; done;']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-postgres-secret
                  key: POSTGRES_USER
      containers:
        - name: movie-service
          image: alexandrevb/movie-image:v.3.0
          command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: movie-postgres-secret
                  key: POSTGRES_DB
            - name: DATABASE_URI
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@movie-db:5432/$(POSTGRES_DB)"
            - name: CAST_SERVICE_HOST_URL
              value: "http://cast-service:8000/api/v1/casts/"
